### ISSUE TITLE
R-9 Actualizar porte de xcircuit a la versión 3.10.30

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/adJ#9]

**Comment by vtamara** [comment]
El porte de FreeBSD ya está en esa versión: https://cgit.freebsd.org/ports/tree/cad/xcircuit/Makefile?id=d0caaea6d09aa0560815aab0d1c4665e83de4243

**Comment by vtamara** [comment]
El porte para OpenBSD está en 3.7.57 y requiere un parche en configure.in.
https://cvsweb.openbsd.org/ports/cad/xcircuit/

**Comment by vtamara** [comment]
Se copia en /usr/ports/mystuff/cad/xcircuit
Se modifica versión en Makefile
Se ajustan checksum con make makesum
Se ajusta versión de autoconfs a una usada por más portes
Al compilar se ve que requiere cairo por lo que se agrega dependencia y para que encuentre encabezado se ajusta CFLAGS

Se logra compilación

**Comment by vtamara** [comment]
Al ejecutar rapidamente termina con SEGMENTATON FAULT

**Comment by vtamara** [comment]
Se ve que el porte de FreeBSD usa TK8.6 se intenta con ese --que requiere -lpthread

**Comment by vtamara** [comment]
Al ejecutar continua presentando segmentation fault.
Ejecutando paso a paso xcircexe con gdb xcircexe con esta secuencia:
break GUI_init
r
n
Se detiene extrañamente en algo de ctype:
(gdb) n                                                                         
0x00000a012b9c1f9d      174             return ((_tolower_tab_ + 1)[_c]);       
(gdb) bt                                                                        
#0  0x00000a012b9c1f9d in GUI_init (objc=1, objv=0xa014711f4d8) at ctype.h:174  
#1  0x00000a012b9c7925 in xctcl_start (clientData=Unhandled dwarf expression opcode 0xa3
) at tclxcircuit.c:10175                                                        
#2  0x00000a0187c3b898 in Tcl_EvalObjv () from /usr/local/lib/libtcl86.so.1.8   

Lo que nos sugiere recompilar Tcl y Tk en adJ con el soporte más completo de xlocale.

**Comment by vtamara** [comment]
Se recompila la versión 3.7.57 con TK 8.6 y se comprueba que opera bien.

**Comment by vtamara** [comment]
Se encuentra hilo de soporte relacionado: https://github.com/RTimothyEdwards/XCircuit/issues/10

Que sugiere usar lo que hay en master de git://opencircuitdesign.com/xcircuit
Al momento de este escrito git log del master de ese da lo mismo que el master de github --que es más fácil de configurar en el porte. Por lo que se usa el de github.

**Comment by vtamara** [comment]
Sin ayuda de persona interesada
